const _ = require('node-validator')

module.exports = _.isObject()
  .withOptional('name', _.isString())
  .withOptional('description', _.isString())
  .withOptional('cover_picture', _.isString())
  .withOptional('icone_picture', _.isString())
  .withOptional('grant_publish', _.isString())
  .withOptional('grant_create_event', _.isString())
  .withOptional('cover_picture', _.isString())
  .withOptional('privacy', _.isString())
  .withOptional('managers', _.isString())
  .withOptional('members', _.isString())
  .withOptional('events', _.isString())
